### ISSUE TITLE
Unsure if it's working

### ISSUE THREAD

**Issue by GregariousJB** [CrimsonMods/CrimsonDropRate#2]
Game v1.0.8
CrimsonDropRate v0.2.1

Can you confirm that this mod is working? I set `DropRateModifier = 100` just to see if it's working right, but I don't see any difference in rarer items dropping more frequently, which seems to be the point of this mod judging by the screenshot in the mod description. Can you explain what this mod does in more detail? At 100, if I break stones, should they be dropping clay, gems, etc all the time?

Maybe including an example use-case in the description would help users know if it's working right.

**Comment by SkyTech6** [comment]
readme updated to make it more clear how this works. 

A table with drop rate 0.001 (lowest in game) would be 0.1 with a modifier of 100. Most "rare" drops are 0.00(1-5).
