### ISSUE TITLE
Not working, throwing an error

### ISSUE THREAD

**Issue by NextNepper** [CrimsonMods/CrimsonDropRate#3]
Error from log file:
```
[Info   :CrimsonDropRate] Changing drop rate values. Modifier: 2
[Error  :CrimsonDropRate] An attempt was made to load a program with an incorrect format. (0x8007000B)
```
I have installed required mods for this mod to work: bloodstone 0.2.2 and BepInExPack_V_Rising v1.691.3 using r2modman. It probably needs an update.

**Comment by SkyTech6** [comment]
Updated, get the new 1.0.2 release either here on Github or from Thunderstore.
